@startuml
'https://plantuml.com/class-diagram

interface Interface1{
       operation1();
       operation2();
       operation3();
       operation4();
       operation5();

}

class A{}
class B{}
class C{}
class D{}

A ..> Interface1
C ..> Interface1

Interface1 <|.. B
Interface1 <|.. D
@enduml